export const questions = [
  {questionNo: 1, questionText: 'Caring for people who have suffered is an important virtue.'},
  {questionNo: 2, questionText: 'I believe that compassion for those who are suffering is one of the most crucial virtues.'},
  {questionNo: 3, questionText: 'We should all care for people who are in emotional pain'},
  {questionNo: 4, questionText: 'I am empathetic toward those people who have suffered in their lives.'},
  {questionNo: 5, questionText: 'Everyone should try to comfort people who are going through something hard.'},
  {questionNo: 6, questionText: 'It pains me when I see someone ignoring the needs of another human being.'},
  {questionNo: 7, questionText: 'The world would be a better place if everyone made the same amount of money.'},
  {questionNo: 8, questionText: 'Our society would have fewer problems if people had the same income.'},
  {questionNo: 9, questionText: 'I believe that everyone should be given the same quantity of resources in life.'},
  {questionNo: 10, questionText: 'I believe it would be ideal if everyone in society wound up with roughly the same amount of money.'},
  {questionNo: 11, questionText: 'When people work together toward a common goal, they should share the rewards equally, even if some worked harder on it.'},
  {questionNo: 12, questionText: 'I get upset when some people have a lot more money than others in my country.'},
  {questionNo: 13, questionText: 'I think people who are more hard-working should end up with more money.'},
  {questionNo: 14, questionText: 'I think people should be rewarded in proportion to what they contribute.'},
  {questionNo: 15, questionText: 'The effort a worker puts into a job ought to be reflected in the size of a raise they receive.'},
  {questionNo: 16, questionText: 'It makes me happy when people are recognized on their merits.'},
  {questionNo: 17, questionText: 'In a fair society, those who work hard should live with higher standards of living.'},
  {questionNo: 18, questionText: 'I feel good when I see cheaters get caught and punished.'},
  {questionNo: 19, questionText: 'I think children should be taught to be loyal to their country.'},
  {questionNo: 20, questionText: 'It upsets me when people have no loyalty to their country.'},
  {questionNo: 21, questionText: 'Everyone should love their own community.'},
  {questionNo: 22, questionText: 'Everyone should defend their country, if called upon. '},
  {questionNo: 23, questionText: 'Everyone should feel proud when a person in their community wins in an international competition.'},
  {questionNo: 24, questionText: 'I believe the strength of a sports team comes from the loyalty of its members to each other.'},
  {questionNo: 25, questionText: 'I think it is important for societies to cherish their traditional values.'},
  {questionNo: 26, questionText: 'I feel that most traditions serve a valuable function in keeping society orderly'},
  {questionNo: 27, questionText: 'I think obedience to parents is an important virtue. '},
  {questionNo: 28, questionText: 'We all need to learn from our elders. '},
  {questionNo: 29, questionText: 'I believe that one of the most important values to teach children is to have respect for authority.'},
  {questionNo: 30, questionText: 'I think having a strong leader is good for society.'},
  {questionNo: 31, questionText: 'I think the human body should be treated like a temple, housing something sacred within.'},
  {questionNo: 32, questionText: 'I believe chastity is an important virtue.'},
  {questionNo: 33, questionText: 'It upsets me when people use foul language like it is nothing.'},
  {questionNo: 34, questionText: 'If I found out that an acquaintance had an unusual but harmless sexual fetish I would feel uneasy about them'},
  {questionNo: 35, questionText: 'People should try to use natural medicines rather than chemically identical human-made ones.'},
  {questionNo: 36, questionText: 'I admire people who keep their virginity until marriage.'},
  ];
